-- ============================================
-- 课件资源导入SQL
-- 课程: BNU-1002842007 数据库系统原理
-- 共 148 个课件
-- ============================================

-- course_id 和 knowledge_point_id 后续手动关联

INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '10、数据库结构调整_数据库结构调整', '课件\\10、数据库结构调整_数据库结构调整.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '11、SQL调优_SQL调优', '课件\\11、SQL调优_SQL调优.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '12、性能调优_性能调优', '课件\\12、性能调优_性能调优.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '1、认识Oracle_认识Oracle', '课件\\1、认识Oracle_认识Oracle.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '2、表空间管理_表空间管理', '课件\\2、表空间管理_表空间管理.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '3、表的创建与删除_表的创建于删除', '课件\\3、表的创建与删除_表的创建于删除.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '4、权限和对象管理_权限和对象管理', '课件\\4、权限和对象管理_权限和对象管理.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '5、数据查询_数据查询', '课件\\5、数据查询_数据查询.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '6、触发器_触发器', '课件\\6、触发器_触发器.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '7、游标_游标', '课件\\7、游标_游标.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '8、事务并发控制_事务并发控制', '课件\\8、事务并发控制_事务并发控制.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '9、备份与恢复_备份与恢复', '课件\\9、备份与恢复_备份与恢复.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB事务_GaussDB事务ppt', '课件\\GaussDB事务_GaussDB事务ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB事务_GaussDB事务报告提纲', '课件\\GaussDB事务_GaussDB事务报告提纲.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB事务_GaussDB事务报告样板', '课件\\GaussDB事务_GaussDB事务报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB单表查询_GaussDB单表查询ppt', '课件\\GaussDB单表查询_GaussDB单表查询ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB单表查询_GaussDB单表查询报告样板', '课件\\GaussDB单表查询_GaussDB单表查询报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB单表查询_GaussDB单表查询报告模板', '课件\\GaussDB单表查询_GaussDB单表查询报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB存储过程与函数_GaussDB存储过程与函数ppt', '课件\\GaussDB存储过程与函数_GaussDB存储过程与函数ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB存储过程与函数_GaussDB存储过程与函数报告样板', '课件\\GaussDB存储过程与函数_GaussDB存储过程与函数报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB存储过程与函数_GaussDB存储过程与函数报告模板', '课件\\GaussDB存储过程与函数_GaussDB存储过程与函数报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB完整性约束和触发器_GaussDB完整性约束和触发器ppt', '课件\\GaussDB完整性约束和触发器_GaussDB完整性约束和触发器ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB完整性约束和触发器_GaussDB完整性约束和触发器报告样板', '课件\\GaussDB完整性约束和触发器_GaussDB完整性约束和触发器报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB完整性约束和触发器_GaussDB完整性约束和触发器报告模板', '课件\\GaussDB完整性约束和触发器_GaussDB完整性约束和触发器报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB数据定义与修改_GaussDB数据定义与修改ppt', '课件\\GaussDB数据定义与修改_GaussDB数据定义与修改ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB数据定义与修改_GaussDB数据定义与修改报告样板', '课件\\GaussDB数据定义与修改_GaussDB数据定义与修改报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB数据定义与修改_GaussDB数据定义与修改报告模板', '课件\\GaussDB数据定义与修改_GaussDB数据定义与修改报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB登录_GaussDB登录指南', '课件\\GaussDB登录_GaussDB登录指南.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB索引与查询优化_GaussDB索引与查询优化ppt', '课件\\GaussDB索引与查询优化_GaussDB索引与查询优化ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB索引与查询优化_GaussDB索引与查询优化报告模板', '课件\\GaussDB索引与查询优化_GaussDB索引与查询优化报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB索引与查询优化_GaussDB索引和性能优化报告样板', '课件\\GaussDB索引与查询优化_GaussDB索引和性能优化报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB视图与访问控制_GaussDB视图与访问控制ppt', '课件\\GaussDB视图与访问控制_GaussDB视图与访问控制ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB视图与访问控制_GaussDB视图与访问控制报告样板', '课件\\GaussDB视图与访问控制_GaussDB视图与访问控制报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB视图与访问控制_GaussDB视图与访问控制报告模板', '课件\\GaussDB视图与访问控制_GaussDB视图与访问控制报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB高级查询_GaussDB高级查询ppt', '课件\\GaussDB高级查询_GaussDB高级查询ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB高级查询_GaussDB高级查询报告样板', '课件\\GaussDB高级查询_GaussDB高级查询报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'GaussDB高级查询_GaussDB高级查询报告模版', '课件\\GaussDB高级查询_GaussDB高级查询报告模版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'JDBC实验环境配置ppt_JDBC实验环境配置ppt', '课件\\JDBC实验环境配置ppt_JDBC实验环境配置ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'JSP案例样板_JSP', '课件\\JSP案例样板_JSP.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'Oracle安装与配置（带解说）_Oralce安装与配置', '课件\\Oracle安装与配置（带解说）_Oralce安装与配置.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：PostgreSQL 10 安装指导_实验 PostgreSQL 10 安装导引', '课件\\PPT：PostgreSQL 10 安装指导_实验 PostgreSQL 10 安装导引.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：PostgreSQL 11 安装指导_实验 PostgreSQL 11 安装导引 ppt', '课件\\PPT：PostgreSQL 11 安装指导_实验 PostgreSQL 11 安装导引 ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：PostgreSQL 9 安装指导_实验 PostgreSQL 9 安装导引', '课件\\PPT：PostgreSQL 9 安装指导_实验 PostgreSQL 9 安装导引.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：实验辅导_实验辅导PPT', '课件\\PPT：实验辅导_实验辅导PPT.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：实验辅导_实验辅导ppt：基于SQL的数据定义与修改', '课件\\PPT：实验辅导_实验辅导ppt：基于SQL的数据定义与修改.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'PPT：实验辅导_数据库_表基本操作', '课件\\PPT：实验辅导_数据库_表基本操作.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'Python连接Gauss DB_Python连接GaussDB ppt', '课件\\Python连接Gauss DB_Python连接GaussDB ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'Python连接Gauss DB_Python连接GaussDB报告样板', '课件\\Python连接Gauss DB_Python连接GaussDB报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'Python连接Gauss DB_Python连接GaussDB报告模板', '课件\\Python连接Gauss DB_Python连接GaussDB报告模板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'SQLServer安装操作基础（带解说）_SQLServer安装操作基础', '课件\\SQLServer安装操作基础（带解说）_SQLServer安装操作基础.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, 'python环境配置_python环境配置', '课件\\python环境配置_python环境配置.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '大数据技术ppt_第八章ppt精炼版', '课件\\大数据技术ppt_第八章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '大数据技术ppt_第八章ppt详细版', '课件\\大数据技术ppt_第八章ppt详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '学员账号_学习账号（仅供GaussDB学习使用）', '课件\\学员账号_学习账号（仅供GaussDB学习使用）.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '安装配置及实验操作指导ppt_安装配置及实验操作指导', '课件\\安装配置及实验操作指导ppt_安装配置及实验操作指导.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '安装配置及实验操作过程说明文档_安装配置及实验操作过程说明文档', '课件\\安装配置及实验操作过程说明文档_安装配置及实验操作过程说明文档.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '安装配置及实验操作过程说明文档_实验操作过程', '课件\\安装配置及实验操作过程说明文档_实验操作过程.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验内容：概念与原理简述_ORM概念与原理简述', '课件\\实验内容：概念与原理简述_ORM概念与原理简述.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告参考样板_实验报告参考样板1', '课件\\实验报告参考样板_实验报告参考样板1.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告参考样板_实验报告参考样板2', '课件\\实验报告参考样板_实验报告参考样板2.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告参考样板_实验报告参考样板3', '课件\\实验报告参考样板_实验报告参考样板3.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_事务与加密实验报告提纲', '课件\\实验报告提纲_事务与加密实验报告提纲.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_实验基本要求', '课件\\实验报告提纲_实验基本要求.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_实验报告提纲', '课件\\实验报告提纲_实验报告提纲.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_实验报告提纲_基于SQL的数据定义与修改', '课件\\实验报告提纲_实验报告提纲_基于SQL的数据定义与修改.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_实验报告提纲pdf版', '课件\\实验报告提纲_实验报告提纲pdf版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲_实验报告提纲：数据库_表的基本操作', '课件\\实验报告提纲_实验报告提纲：数据库_表的基本操作.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲：网上书店_实验报告提纲', '课件\\实验报告提纲：网上书店_实验报告提纲.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告提纲：高级数据查询_实验报告提纲：高级数据查询', '课件\\实验报告提纲：高级数据查询_实验报告提纲：高级数据查询.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板1_实验报告样板1', '课件\\实验报告样板1_实验报告样板1.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板2_实验报告样板2', '课件\\实验报告样板2_实验报告样板2.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板3_实验报告样板3', '课件\\实验报告样板3_实验报告样板3.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_实验报告样板', '课件\\实验报告样板_实验报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_实验报告样板1', '课件\\实验报告样板_实验报告样板1.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_实验报告样板2', '课件\\实验报告样板_实验报告样板2.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_实验报告样板：完整性约束与触发器', '课件\\实验报告样板_实验报告样板：完整性约束与触发器.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_实验报告样板：视图与访问控制', '课件\\实验报告样板_实验报告样板：视图与访问控制.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_数据库_表的基本操作样板1', '课件\\实验报告样板_数据库_表的基本操作样板1.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板_数据库_表的基本操作样板2', '课件\\实验报告样板_数据库_表的基本操作样板2.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板：JDBC与PL_pgSQL_实验报告样板：JDBC与PL_pgSQL', '课件\\实验报告样板：JDBC与PL_pgSQL_实验报告样板：JDBC与PL_pgSQL.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告样板：网上书店_实验报告样板', '课件\\实验报告样板：网上书店_实验报告样板.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告要求_实验报告要求', '课件\\实验报告要求_实验报告要求.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准_事务与加密实验报告评分标准', '课件\\实验报告评分标准_事务与加密实验报告评分标准.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准_实验报告评分标准', '课件\\实验报告评分标准_实验报告评分标准.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准_实验报告评分标准_基于SQL的数据定义与修改', '课件\\实验报告评分标准_实验报告评分标准_基于SQL的数据定义与修改.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准_实验报告评分标准：数据库_表的基本操作', '课件\\实验报告评分标准_实验报告评分标准：数据库_表的基本操作.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准：网上书店_实验报告评分标准', '课件\\实验报告评分标准：网上书店_实验报告评分标准.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验报告评分标准：高级数据查询_实验报告评分标准：高级数据查询', '课件\\实验报告评分标准：高级数据查询_实验报告评分标准：高级数据查询.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导ppt_实验指导ppt', '课件\\实验指导ppt_实验指导ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_PD实验指导', '课件\\实验指导书_PD实验指导.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_事务与加密实验指导', '课件\\实验指导书_事务与加密实验指导.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_实验指导', '课件\\实验指导书_实验指导.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_实验指导书', '课件\\实验指导书_实验指导书.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_实验指导：完整性约束 触发器', '课件\\实验指导书_实验指导：完整性约束 触发器.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_实验指导：嵌入式pgSQL', '课件\\实验指导书_实验指导：嵌入式pgSQL.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书_实验指导：数据库_表的基本操作', '课件\\实验指导书_实验指导：数据库_表的基本操作.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书：网上书店_实验指导书', '课件\\实验指导书：网上书店_实验指导书.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验指导书：高级数据查询_实验指导：高级数据查询', '课件\\实验指导书：高级数据查询_实验指导：高级数据查询.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验环境搭建_实验环境搭建', '课件\\实验环境搭建_实验环境搭建.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验评分标准_实验评分标准', '课件\\实验评分标准_实验评分标准.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导PPT_ppt', '课件\\实验辅导PPT_ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt_实验指导ppt', '课件\\实验辅导ppt_实验指导ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt_实验辅导ppt', '课件\\实验辅导ppt_实验辅导ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt_实验辅导ppt：完整性约束与触发器', '课件\\实验辅导ppt_实验辅导ppt：完整性约束与触发器.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt_实验辅导ppt：视图与访问控制', '课件\\实验辅导ppt_实验辅导ppt：视图与访问控制.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt：JDBC与PL_pgSQL_PLpgSQL过程语言', '课件\\实验辅导ppt：JDBC与PL_pgSQL_PLpgSQL过程语言.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt：JDBC与PL_pgSQL_实验辅导ppt JDBC与PL_pgSQL', '课件\\实验辅导ppt：JDBC与PL_pgSQL_实验辅导ppt JDBC与PL_pgSQL.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '实验辅导ppt：高级数据查询_ppt', '课件\\实验辅导ppt：高级数据查询_ppt.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '嵌入式pgSQL_ECPG 示例_嵌入式pgSQL_ECPG 示例', '课件\\嵌入式pgSQL_ECPG 示例_嵌入式pgSQL_ECPG 示例.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '总结与提高（总时长8分20秒）_第一章总结与提高---教学内容', '课件\\总结与提高（总时长8分20秒）_第一章总结与提高---教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '报告互评现场瞬间_报告互评现场瞬间', '课件\\报告互评现场瞬间_报告互评现场瞬间.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第1讲 数据结构的基础概念（总时长12分钟）_第1讲数据结构的基础概念--教学内容', '课件\\第1讲 数据结构的基础概念（总时长12分钟）_第1讲数据结构的基础概念--教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第1讲 线性表的概念（总时长9分20秒）_第1讲线性表的概念--教学内容讲义', '课件\\第1讲 线性表的概念（总时长9分20秒）_第1讲线性表的概念--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第2讲 数据结构的内容（总时长5分29秒）_第2讲数据结构的内容--教学内容', '课件\\第2讲 数据结构的内容（总时长5分29秒）_第2讲数据结构的内容--教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第2讲 线性表的顺序存储（总时长13分）_第2讲线性表的顺序存储--教学内容讲义', '课件\\第2讲 线性表的顺序存储（总时长13分）_第2讲线性表的顺序存储--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第3讲 数据结构与c语言表示（总时长7分32秒）_第3讲数据结构与C语言表示--教学内容', '课件\\第3讲 数据结构与c语言表示（总时长7分32秒）_第3讲数据结构与C语言表示--教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第3讲 线性表顺序结构应用示例及小结（总时长7分57秒）_第3讲线性表顺序结构应用举例及小结--教学内容讲义', '课件\\第3讲 线性表顺序结构应用示例及小结（总时长7分57秒）_第3讲线性表顺序结构应用举例及小结--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第4讲 算法性能评价（总时长8分06秒）_第4讲算法性能评价--教学内容', '课件\\第4讲 算法性能评价（总时长8分06秒）_第4讲算法性能评价--教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第4讲 线性表的链式存储（总时长10分20秒）_第4讲线性表的链式存储--教学内容讲义', '课件\\第4讲 线性表的链式存储（总时长10分20秒）_第4讲线性表的链式存储--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第5讲 单链表的基本运算（总时长20分58秒）_第5讲单链表的基本运算--教学内容讲义', '课件\\第5讲 单链表的基本运算（总时长20分58秒）_第5讲单链表的基本运算--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第5讲 算法与算法的描述（总时长14分59秒）_第5讲算法与算法描述--教学内容', '课件\\第5讲 算法与算法的描述（总时长14分59秒）_第5讲算法与算法描述--教学内容.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第6讲 单链表运算的应用示例及小结（总时长10分47秒）_第6讲单链表的应用实例及小结--教学内容讲义', '课件\\第6讲 单链表运算的应用示例及小结（总时长10分47秒）_第6讲单链表的应用实例及小结--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第7讲 循环链表（总时长7分05秒）_第7讲循环链表--教学内容讲义', '课件\\第7讲 循环链表（总时长7分05秒）_第7讲循环链表--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第8讲 双向链表（总时长7分47秒）_第8讲双向链表--教学内容讲义', '课件\\第8讲 双向链表（总时长7分47秒）_第8讲双向链表--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第9讲 静态链表（总时长6分24秒）_第9讲静态链表--教学内容讲义', '课件\\第9讲 静态链表（总时长6分24秒）_第9讲静态链表--教学内容讲义.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第一章ppt_第一章 ppt (精简版)', '课件\\第一章ppt_第一章 ppt (精简版).pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第一章ppt_第一章ppt （详细版）', '课件\\第一章ppt_第一章ppt （详细版）.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第七章ppt_第七章ppt精炼版', '课件\\第七章ppt_第七章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第七章ppt_第七章ppt（上1）详细版', '课件\\第七章ppt_第七章ppt（上1）详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第七章ppt_第七章ppt（上2）详细版', '课件\\第七章ppt_第七章ppt（上2）详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第七章ppt_第七章ppt（下）详细版', '课件\\第七章ppt_第七章ppt（下）详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第三章ppt_第三章ppt上详细版', '课件\\第三章ppt_第三章ppt上详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第三章ppt_第三章ppt下详细版', '课件\\第三章ppt_第三章ppt下详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第三章ppt_第三章ppt精炼版', '课件\\第三章ppt_第三章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第二章ppt_第二章ppt精简版', '课件\\第二章ppt_第二章ppt精简版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第二章ppt_第二章ppt详细版', '课件\\第二章ppt_第二章ppt详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第五章ppt_第五章ppt精炼版', '课件\\第五章ppt_第五章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第五章ppt_第五章ppt详细版（上）', '课件\\第五章ppt_第五章ppt详细版（上）.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第五章ppt_第五章ppt详细版（下）', '课件\\第五章ppt_第五章ppt详细版（下）.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第六章ppt_第六章ppt精炼版', '课件\\第六章ppt_第六章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第六章ppt_第六章ppt（上）详细版', '课件\\第六章ppt_第六章ppt（上）详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第六章ppt_第六章ppt（下）详细版', '课件\\第六章ppt_第六章ppt（下）详细版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第四章ppt_第四章ppt精炼版', '课件\\第四章ppt_第四章ppt精炼版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第四章ppt_第四章ppt（上）详尽版', '课件\\第四章ppt_第四章ppt（上）详尽版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '第四章ppt_第四章ppt（下）详尽版', '课件\\第四章ppt_第四章ppt（下）详尽版.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '补充资源1-算法时间复杂度练习_算法时间复杂度练习', '课件\\补充资源1-算法时间复杂度练习_算法时间复杂度练习.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '补充资源3-单链表初始化解析_单链表初始化解析', '课件\\补充资源3-单链表初始化解析_单链表初始化解析.pdf', 'pdf');
INSERT INTO courseware_resource (course_id, knowledge_point_id, title, file_path, file_type) VALUES (4, NULL, '附加材料：ODBC举例_ODBC举例', '课件\\附加材料：ODBC举例_ODBC举例.pdf', 'pdf');
